### ISSUE TITLE
Add explicit SIMD for aarch64 platforms.

### ISSUE THREAD

**Issue by cessen** [cessen/str_indices#10]
Aarch64 simd intrinsics are stable as of Rust 1.59 (although due to a documentation bug are falsely still marked as unstable: https://github.com/rust-lang/stdarch/issues/1268).  This means we can now add proper SIMD acceleration for those platforms.

I don't currently have an aarch64 system to test on, so I won't attempt to implement myself.  But if anyone would like to take a crack at it, it mostly just consists of making a new impl of the `ByteChunk` trait in `src/byte_chunk.rs` for the appropriate `core::arch::aarch64` type.  Although there may be some complexities with CPU features, etc.

**Comment by CeleritasCelery** [comment]
I took the initiative to implement this on Aarch64 on my M1. 

https://github.com/CeleritasCelery/str_indices/commit/2757d698e6c857887f4f641ffb31100019fd981d

The tests pass and the fuzzer didn't find anything, but this code is significantly slower then the previous non-SIMD version 😢. 

[here](https://gist.github.com/CeleritasCelery/fdd9dfc14bb790c78e2f48bd0fff2864) is the results. We have 29 improvements (around 2x), and 79 regressions (2-10x). 

I am at a loss to explain the slow down. Would you be able to take a look and see if I got something fundamentally wrong?

**Comment by cessen** [comment]
Thanks so much for taking a crack at this!

If you just want to submit a WIP PR directly, that would be fine.  Even if it isn't up to snuff yet, that will make reviewing it a little easier.

Either way, I'll try to get to it within the next couple of weeks.
