### ISSUE TITLE
Question about SSE intrinsics 

### ISSUE THREAD

**Issue by CeleritasCelery** [cessen/str_indices#18]
I was looking at a way to simplify the CRLF routine. I know how to do it in neon, but can't seem to figure it out in SSE. Essentially I need something like [vextq_u8](https://developer.arm.com/architectures/instruction-sets/intrinsics/#q=vextq_u8) that allows you shuffle elements between vectors so that I can take the bottom 8-bits of one vector and shift it into the top of another. I was going to use the [shuffle](https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#ig_expand=695,7048,696,5398,5398&cats=Swizzle&ssetechs=SSE) commands but they only operate on 16 bit values. There doesn't even seem to be a good get/set method. A basic 8-bit set isn't even [available till SEE4.1](https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#ig_expand=695,7048,696,5398,5398,4212,4210,4210,4210&text=_mm_insert_epi8). 

Perhaps you can direct me on how best to solve this with SEE1.

**Comment by cessen** [comment]
Sorry for the delayed response on this!

I don't know of a way to do this off the top of my head.  And indeed, x86/64 SIMD instructions are often limited in odd, arbitrary ways.  So it may simply not be possible.  Not sure, though.

**Comment by cessen** [comment]
Addressed by #21.
